config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:home]
  

  
  scope module: 'admin' do
    resources :cases
    resources :legal_forms
    resources :glossaries
    resources :case_requests
    resources :form_requests
    resources :glossary_requests
    resources :questions
    resources :messages
    resources :users
  end

  get 'login' => 'session#new'

  post 'login' => 'session#create'

  get 'logout' => 'session#destroy'
  
  get 'home' => 'users#home'
  
  get 'ask_lea' => 'users#ask_lea'
  
  post 'post_message' => 'messages#post_message'
  
  post 'admin_post_message' => 'admin/users#post_message'
  
  
  get 'answer_question' => 'questions#answer_question'
  
  get 'admin_home' => 'admin/users#home'
  

  root 'session#index'
end

app/controllers/admin/legal_forms_controller.rb
class Admin::LegalFormsController < AdminController
  before_action :set_legal_form, only: [:show, :edit, :update, :destroy]

  # GET /legal_forms
  # GET /legal_forms.json
  def index
    @legal_forms = LegalForm.all
  end

  # GET /legal_forms/1
  # GET /legal_forms/1.json
  def show
  end

  # GET /legal_forms/new
  def new
    @legal_form = LegalForm.new
  end

  # GET /legal_forms/1/edit
  def edit
  end

  # POST /legal_forms
  # POST /legal_forms.json
  def create
    @legal_form = LegalForm.new(legal_form_params)

    respond_to do |format|
      if @legal_form.save
        format.html { redirect_to @legal_form, notice: 'Legal form was successfully created.' }
        format.json { render :show, status: :created, location: @legal_form }
      else
        format.html { render :new }
        format.json { render json: @legal_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legal_forms/1
  # PATCH/PUT /legal_forms/1.json
  def update
    respond_to do |format|
      if @legal_form.update(legal_form_params)
        format.html { redirect_to @legal_form, notice: 'Legal form was successfully updated.' }
        format.json { render :show, status: :ok, location: @legal_form }
      else
        format.html { render :edit }
        format.json { render json: @legal_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legal_forms/1
  # DELETE /legal_forms/1.json
  def destroy
    @legal_form.destroy
    respond_to do |format|
      format.html { redirect_to legal_forms_url, notice: 'Legal form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legal_form
      @legal_form = LegalForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def legal_form_params
      params.require(:legal_form).permit(:legal_form_title, :legal_form_content, :legal_form_doc, :legal_form_docx, :legal_form_related_forms, :credit, :legal_form_created, :legal_form_updated, :legal_form_credit, :legal_form_is_lea_output, :legal_form_pdf)
    end
end

app/controllers/legal_forms_controller.rb
class LegalFormsController < ApplicationController
  before_action :set_legal_form, only: [:show, :edit, :update, :destroy]

  # GET /legal_forms
  # GET /legal_forms.json
  def index
    @legal_forms = LegalForm.all
  end

  # GET /legal_forms/1
  # GET /legal_forms/1.json
  def show
  end

  # GET /legal_forms/new
  def new
    @legal_form = LegalForm.new
  end

  # GET /legal_forms/1/edit
  def edit
  end

  # POST /legal_forms
  # POST /legal_forms.json
  def create
    @legal_form = LegalForm.new(legal_form_params)

    respond_to do |format|
      if @legal_form.save
        format.html { redirect_to @legal_form, notice: 'Legal form was successfully created.' }
        format.json { render :show, status: :created, location: @legal_form }
      else
        format.html { render :new }
        format.json { render json: @legal_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legal_forms/1
  # PATCH/PUT /legal_forms/1.json
  def update
    respond_to do |format|
      if @legal_form.update(legal_form_params)
        format.html { redirect_to @legal_form, notice: 'Legal form was successfully updated.' }
        format.json { render :show, status: :ok, location: @legal_form }
      else
        format.html { render :edit }
        format.json { render json: @legal_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legal_forms/1
  # DELETE /legal_forms/1.json
  def destroy
    @legal_form.destroy
    respond_to do |format|
      format.html { redirect_to legal_forms_url, notice: 'Legal form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legal_form
      @legal_form = LegalForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def legal_form_params
      params.require(:legal_form).permit(:string, :text)
    end
end

app/helpers/legal_forms_helper.rb
module LegalFormsHelper
end

app/views/admin/legal_forms/_form.html.haml
= form_for @legal_form do |f|
  - if @legal_form.errors.any?
    #error_explanation
      %h2= "#{pluralize(@legal_form.errors.count, "error")} prohibited this legal_form from being saved:"
      %ul
        - @legal_form.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :legal_form_title
    = f.text_area :legal_form_title
  .field
    = f.label :legal_form_content
    = f.text_area :legal_form_content
  .field
    = f.label :legal_form_doc
    = f.text_area :legal_form_doc
  .field
    = f.label :legal_form_docx
    = f.text_area :legal_form_docx
  .field
    = f.label :legal_form_related_forms
    = f.text_area :legal_form_related_forms
  .field
    = f.label :credit
    = f.number_field :credit
  .field
    = f.label :legal_form_created
    = f.datetime_select :legal_form_created
  .field
    = f.label :legal_form_updated
    = f.datetime_select :legal_form_updated
  .field
    = f.label :legal_form_credit
    = f.number_field :legal_form_credit
  .field
    = f.label :legal_form_is_lea_output
    = f.number_field :legal_form_is_lea_output
  .field
    = f.label :legal_form_pdf
    = f.text_area :legal_form_pdf
  .actions
    = f.submit 'Save'

app/views/admin/legal_forms/edit.html.haml
%h1 Editing legal_form

= render 'form'

= link_to 'Show', @legal_form
\|
= link_to 'Back', legal_forms_path

app/views/admin/legal_forms/index.html.haml
%h1 Listing legal_forms

%table
  %thead
    %tr
      %th Legal form title
      %th Legal form content
      %th Legal form doc
      %th Legal form docx
      %th Legal form related forms
      %th Credit
      %th Legal form created
      %th Legal form updated
      %th Legal form credit
      %th Legal form is lea output
      %th Legal form pdf
      %th
      %th
      %th

  %tbody
    - @legal_forms.each do |legal_form|
      %tr
        %td= legal_form.legal_form_title
        %td= legal_form.legal_form_content
        %td= legal_form.legal_form_doc
        %td= legal_form.legal_form_docx
        %td= legal_form.legal_form_related_forms
        %td= legal_form.credit
        %td= legal_form.legal_form_created
        %td= legal_form.legal_form_updated
        %td= legal_form.legal_form_credit
        %td= legal_form.legal_form_is_lea_output
        %td= legal_form.legal_form_pdf
        %td= link_to 'Show', legal_form
        %td= link_to 'Edit', edit_legal_form_path(legal_form)
        %td= link_to 'Destroy', legal_form, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Legal form', new_legal_form_path

app/views/admin/legal_forms/new.html.haml
%h1 New legal_form

= render 'form'

= link_to 'Back', legal_forms_path

app/views/admin/legal_forms/show.html.haml
%p#notice= notice

%p
  %b Legal form title:
  = @legal_form.legal_form_title
%p
  %b Legal form content:
  = @legal_form.legal_form_content
%p
  %b Legal form doc:
  = @legal_form.legal_form_doc
%p
  %b Legal form docx:
  = @legal_form.legal_form_docx
%p
  %b Legal form related forms:
  = @legal_form.legal_form_related_forms
%p
  %b Credit:
  = @legal_form.credit
%p
  %b Legal form created:
  = @legal_form.legal_form_created
%p
  %b Legal form updated:
  = @legal_form.legal_form_updated
%p
  %b Legal form credit:
  = @legal_form.legal_form_credit
%p
  %b Legal form is lea output:
  = @legal_form.legal_form_is_lea_output
%p
  %b Legal form pdf:
  = @legal_form.legal_form_pdf

= link_to 'Edit', edit_legal_form_path(@legal_form)
\|
= link_to 'Back', legal_forms_path