config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:home]
  

  
  scope module: 'admin' do
    resources :cases
    resources :legal_forms
    resources :glossaries
    resources :case_requests
    resources :form_requests
    resources :glossary_requests
    resources :questions
    resources :messages
    resources :users
  end

  get 'login' => 'session#new'

  post 'login' => 'session#create'

  get 'logout' => 'session#destroy'
  
  get 'home' => 'users#home'
  
  get 'ask_lea' => 'users#ask_lea'
  
  post 'post_message' => 'messages#post_message'
  
  post 'admin_post_message' => 'admin/users#post_message'
  
  
  get 'answer_question' => 'questions#answer_question'
  
  get 'admin_home' => 'admin/users#home'
  

  root 'session#index'
end

app/models/glossary.rb
class Glossary < ActiveRecord::Base
    fuzzily_searchable :glossary_term
end

app/controllers/admin/glossaries_controller.rb
class Admin::GlossariesController < AdminController
  before_action :set_glossary, only: [:show, :edit, :update, :destroy]

  # GET /glossaries
  # GET /glossaries.json
  def index
    @glossaries = Glossary.all
  end

  # GET /glossaries/1
  # GET /glossaries/1.json
  def show
  end

  # GET /glossaries/new
  def new
    @glossary = Glossary.new
  end

  # GET /glossaries/1/edit
  def edit
  end

  # POST /glossaries
  # POST /glossaries.json
  def create
    @glossary = Glossary.new(glossary_params)

    respond_to do |format|
      if @glossary.save
        format.html { redirect_to @glossary, notice: 'Glossary was successfully created.' }
        format.json { render :show, status: :created, location: @glossary }
      else
        format.html { render :new }
        format.json { render json: @glossary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /glossaries/1
  # PATCH/PUT /glossaries/1.json
  def update
    respond_to do |format|
      if @glossary.update(glossary_params)
        format.html { redirect_to @glossary, notice: 'Glossary was successfully updated.' }
        format.json { render :show, status: :ok, location: @glossary }
      else
        format.html { render :edit }
        format.json { render json: @glossary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /glossaries/1
  # DELETE /glossaries/1.json
  def destroy
    @glossary.destroy
    respond_to do |format|
      format.html { redirect_to glossaries_url, notice: 'Glossary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_glossary
      @glossary = Glossary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def glossary_params
      params.require(:glossary).permit(:glossary_solr, :glossary_term, :glossary_description, :glossary_case_number, :glossary_year, :glossary_month, :glossary_laws, :glossary_reference, :glossary_bir_number, :glossary_bir_year, :glossary_bir_month, :glossary_revenue_number, :glossary_revenue_year, :glossary_revenue_month, :glossary_created, :glossary_updated, :glossary_credit, :glossary_is_lea_output)
    end
end

app/controllers/glossaries_controller.rb
class GlossariesController < ApplicationController
  before_action :set_glossary, only: [:show, :edit, :update, :destroy]

  # GET /glossaries
  # GET /glossaries.json
  def index
    @glossaries = Glossary.all
  end

  # GET /glossaries/1
  # GET /glossaries/1.json
  def show
  end

  # GET /glossaries/new
  def new
    @glossary = Glossary.new
  end

  # GET /glossaries/1/edit
  def edit
  end

  # POST /glossaries
  # POST /glossaries.json
  def create
    @glossary = Glossary.new(glossary_params)

    respond_to do |format|
      if @glossary.save
        format.html { redirect_to @glossary, notice: 'Glossary was successfully created.' }
        format.json { render :show, status: :created, location: @glossary }
      else
        format.html { render :new }
        format.json { render json: @glossary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /glossaries/1
  # PATCH/PUT /glossaries/1.json
  def update
    respond_to do |format|
      if @glossary.update(glossary_params)
        format.html { redirect_to @glossary, notice: 'Glossary was successfully updated.' }
        format.json { render :show, status: :ok, location: @glossary }
      else
        format.html { render :edit }
        format.json { render json: @glossary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /glossaries/1
  # DELETE /glossaries/1.json
  def destroy
    @glossary.destroy
    respond_to do |format|
      format.html { redirect_to glossaries_url, notice: 'Glossary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_glossary
      @glossary = Glossary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def glossary_params
      params.require(:glossary).permit(:string, :string)
    end
end

app/helpers/glossaries_helper.rb
module GlossariesHelper
end

app/views/admin/glossaries/_form.html.haml
= form_for @glossary do |f|
  - if @glossary.errors.any?
    #error_explanation
      %h2= "#{pluralize(@glossary.errors.count, "error")} prohibited this glossary from being saved:"
      %ul
        - @glossary.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :glossary_solr
    = f.text_field :glossary_solr
  .field
    = f.label :glossary_term
    = f.text_field :glossary_term
  .field
    = f.label :glossary_description
    = f.text_area :glossary_description
  .field
    = f.label :glossary_case_number
    = f.text_area :glossary_case_number
  .field
    = f.label :glossary_year
    = f.text_field :glossary_year
  .field
    = f.label :glossary_month
    = f.text_field :glossary_month
  .field
    = f.label :glossary_laws
    = f.text_area :glossary_laws
  .field
    = f.label :glossary_reference
    = f.text_area :glossary_reference
  .field
    = f.label :glossary_bir_number
    = f.text_area :glossary_bir_number
  .field
    = f.label :glossary_bir_year
    = f.text_area :glossary_bir_year
  .field
    = f.label :glossary_bir_month
    = f.text_area :glossary_bir_month
  .field
    = f.label :glossary_revenue_number
    = f.text_area :glossary_revenue_number
  .field
    = f.label :glossary_revenue_year
    = f.text_area :glossary_revenue_year
  .field
    = f.label :glossary_revenue_month
    = f.text_area :glossary_revenue_month
  .field
    = f.label :glossary_created
    = f.datetime_select :glossary_created
  .field
    = f.label :glossary_updated
    = f.datetime_select :glossary_updated
  .field
    = f.label :glossary_credit
    = f.number_field :glossary_credit
  .field
    = f.label :glossary_is_lea_output
    = f.number_field :glossary_is_lea_output
  .actions
    = f.submit 'Save'

app/views/admin/glossaries/edit.html.haml
%h1 Editing glossary

= render 'form'

= link_to 'Show', @glossary
\|
= link_to 'Back', glossaries_path

app/views/admin/glossaries/index.html.haml
%h1 Listing glossaries

%table
  %thead
    %tr
      %th Glossary solr
      %th Glossary term
      %th Glossary description
      %th Glossary case number
      %th Glossary year
      %th Glossary month
      %th Glossary laws
      %th Glossary reference
      %th Glossary bir number
      %th Glossary bir year
      %th Glossary bir month
      %th Glossary revenue number
      %th Glossary revenue year
      %th Glossary revenue month
      %th Glossary created
      %th Glossary updated
      %th Glossary credit
      %th Glossary is lea output
      %th
      %th
      %th

  %tbody
    - @glossaries.each do |glossary|
      %tr
        %td= glossary.glossary_solr
        %td= glossary.glossary_term
        %td= glossary.glossary_description
        %td= glossary.glossary_case_number
        %td= glossary.glossary_year
        %td= glossary.glossary_month
        %td= glossary.glossary_laws
        %td= glossary.glossary_reference
        %td= glossary.glossary_bir_number
        %td= glossary.glossary_bir_year
        %td= glossary.glossary_bir_month
        %td= glossary.glossary_revenue_number
        %td= glossary.glossary_revenue_year
        %td= glossary.glossary_revenue_month
        %td= glossary.glossary_created
        %td= glossary.glossary_updated
        %td= glossary.glossary_credit
        %td= glossary.glossary_is_lea_output
        %td= link_to 'Show', glossary
        %td= link_to 'Edit', edit_glossary_path(glossary)
        %td= link_to 'Destroy', glossary, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Glossary', new_glossary_path

app/views/admin/glossaries/new.html.haml
%h1 New glossary

= render 'form'

= link_to 'Back', glossaries_path

app/views/admin/glossaries/show.html.haml
%p#notice= notice

%p
  %b Glossary solr:
  = @glossary.glossary_solr
%p
  %b Glossary term:
  = @glossary.glossary_term
%p
  %b Glossary description:
  = @glossary.glossary_description
%p
  %b Glossary case number:
  = @glossary.glossary_case_number
%p
  %b Glossary year:
  = @glossary.glossary_year
%p
  %b Glossary month:
  = @glossary.glossary_month
%p
  %b Glossary laws:
  = @glossary.glossary_laws
%p
  %b Glossary reference:
  = @glossary.glossary_reference
%p
  %b Glossary bir number:
  = @glossary.glossary_bir_number
%p
  %b Glossary bir year:
  = @glossary.glossary_bir_year
%p
  %b Glossary bir month:
  = @glossary.glossary_bir_month
%p
  %b Glossary revenue number:
  = @glossary.glossary_revenue_number
%p
  %b Glossary revenue year:
  = @glossary.glossary_revenue_year
%p
  %b Glossary revenue month:
  = @glossary.glossary_revenue_month
%p
  %b Glossary created:
  = @glossary.glossary_created
%p
  %b Glossary updated:
  = @glossary.glossary_updated
%p
  %b Glossary credit:
  = @glossary.glossary_credit
%p
  %b Glossary is lea output:
  = @glossary.glossary_is_lea_output

= link_to 'Edit', edit_glossary_path(@glossary)
\|
= link_to 'Back', glossaries_path