config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:home]
  

  
  scope module: 'admin' do
    resources :cases
    resources :legal_forms
    resources :glossaries
    resources :case_requests
    resources :form_requests
    resources :glossary_requests
    resources :questions
    resources :messages
    resources :users
  end

  get 'login' => 'session#new'

  post 'login' => 'session#create'

  get 'logout' => 'session#destroy'
  
  get 'home' => 'users#home'
  
  get 'ask_lea' => 'users#ask_lea'
  
  post 'post_message' => 'messages#post_message'
  
  post 'admin_post_message' => 'admin/users#post_message'
  
  
  get 'answer_question' => 'questions#answer_question'
  
  get 'admin_home' => 'admin/users#home'
  

  root 'session#index'
end

app/models/form_request.rb
class FormRequest < ActiveRecord::Base
    belongs_to :user
    
    default_scope -> { order(created_at: :asc) }
    validates :user_id, presence: true
end

app/controllers/admin/form_requests_controller.rb
class Admin::FormRequestsController < ApplicationController
  before_action :set_form_request, only: [:show, :edit, :update, :destroy]

  # GET /form_requests
  # GET /form_requests.json
  def index
    @form_requests = FormRequest.all
  end

  # GET /form_requests/1
  # GET /form_requests/1.json
  def show
  end

  # GET /form_requests/new
  def new
    @form_request = FormRequest.new
  end

  # GET /form_requests/1/edit
  def edit
  end

  # POST /form_requests
  # POST /form_requests.json
  def create
    @form_request = FormRequest.new(form_request_params)

    respond_to do |format|
      if @form_request.save
        format.html { redirect_to @form_request, notice: 'Form request was successfully created.' }
        format.json { render :show, status: :created, location: @form_request }
      else
        format.html { render :new }
        format.json { render json: @form_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_requests/1
  # PATCH/PUT /form_requests/1.json
  def update
    respond_to do |format|
      if @form_request.update(form_request_params)
        LegalForm.create(legal_form_title: @form_request.title, legal_form_content: @form_request.content)
        
        @form_request.user.messages.create(content: "The " + @form_request.title + " form is now available at Forms Section.", is_lea_response: true)
        
        @form_request.destroy
        
        format.html { redirect_to @form_request, notice: 'Form request was successfully updated.' }
        format.json { render :show, status: :ok, location: @form_request }
      else
        format.html { render :edit }
        format.json { render json: @form_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_requests/1
  # DELETE /form_requests/1.json
  def destroy
    @form_request.destroy
    respond_to do |format|
      format.html { redirect_to form_requests_url, notice: 'Form request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form_request
      @form_request = FormRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_request_params
      params.require(:form_request).permit(:user_id, :title, :content)
    end
end

app/controllers/form_requests_controller.rb
class FormRequestsController < AdminController
  before_action :set_form_request, only: [:show, :edit, :update, :destroy]

  # GET /form_requests
  # GET /form_requests.json
  def index
    @form_requests = FormRequest.all
  end

  # GET /form_requests/1
  # GET /form_requests/1.json
  def show
  end

  # GET /form_requests/new
  def new
    @form_request = FormRequest.new
  end

  # GET /form_requests/1/edit
  def edit
  end

  # POST /form_requests
  # POST /form_requests.json
  def create
    @form_request = FormRequest.new(form_request_params)

    respond_to do |format|
      if @form_request.save
        format.html { redirect_to @form_request, notice: 'Form request was successfully created.' }
        format.json { render :show, status: :created, location: @form_request }
      else
        format.html { render :new }
        format.json { render json: @form_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_requests/1
  # PATCH/PUT /form_requests/1.json
  def update
    respond_to do |format|
      if @form_request.update(form_request_params)
        format.html { redirect_to @form_request, notice: 'Form request was successfully updated.' }
        format.json { render :show, status: :ok, location: @form_request }
      else
        format.html { render :edit }
        format.json { render json: @form_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_requests/1
  # DELETE /form_requests/1.json
  def destroy
    @form_request.destroy
    respond_to do |format|
      format.html { redirect_to form_requests_url, notice: 'Form request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form_request
      @form_request = FormRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_request_params
      params.require(:form_request).permit(:user_id, :title, :content)
    end
end

app/helpers/form_requests_helper.rb
module FormRequestsHelper
end

app/views/admin/form_requests/_form.html.haml
= form_for @form_request do |f|
  - if @form_request.errors.any?
    #error_explanation
      %h2= "#{pluralize(@form_request.errors.count, "error")} prohibited this form_request from being saved:"
      %ul
        - @form_request.errors.full_messages.each do |msg|
          %li= msg

  %table{:class => "table"}
    %tr.field
      %td= f.label :user
      %td= @form_request.user_id
    %tr.field
      %td= f.label :title
      %td= @form_request.title
    %tr.field
      %td= f.label :content
      %td= f.text_field :content, :class => "form-control"
    .field
      = f.hidden_field :form_request_id, value: @form_request.id
    %tr.actions
      %td= f.submit 'Save', :class => "btn btn-success"
      %td

app/views/admin/form_requests/edit.html.haml
%h1 Adding Form Entry

= render 'form'

= link_to 'Back', form_requests_path, :class => "btn btn-danger"

app/views/admin/form_requests/index.html.haml
%h1 Listing Form Requests

%table{:class => "table"}
  %thead
    %tr
      %th User
      %th Title
      %th Content
      %th

  %tbody
    - @form_requests.each do |form_request|
      %tr
        %td= form_request.user.username
        %td= form_request.title
        %td= form_request.content
        %td= link_to 'Create', edit_form_request_path(form_request), :class => "btn btn-success"

app/views/admin/form_requests/new.html.haml
%h1 New form_request

= render 'form'

= link_to 'Back', form_requests_path

app/views/admin/form_requests/show.html.haml
%p#notice= notice

%p
  %b User:
  = @form_request.user_id
%p
  %b Title:
  = @form_request.title
%p
  %b Content:
  = @form_request.content

= link_to 'Edit', edit_form_request_path(@form_request)
\|
= link_to 'Back', form_requests_path