config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:home]
  

  
  scope module: 'admin' do
    resources :cases
    resources :legal_forms
    resources :glossaries
    resources :case_requests
    resources :form_requests
    resources :glossary_requests
    resources :questions
    resources :messages
    resources :users
  end

  get 'login' => 'session#new'

  post 'login' => 'session#create'

  get 'logout' => 'session#destroy'
  
  get 'home' => 'users#home'
  
  get 'ask_lea' => 'users#ask_lea'
  
  post 'post_message' => 'messages#post_message'
  
  post 'admin_post_message' => 'admin/users#post_message'
  
  
  get 'answer_question' => 'questions#answer_question'
  
  get 'admin_home' => 'admin/users#home'
  

  root 'session#index'
end

app/models/case.rb
class Case < ActiveRecord::Base
    fuzzily_searchable :case_title
end

app/models/case_request.rb
class CaseRequest < ActiveRecord::Base
    belongs_to :user
    
    default_scope -> { order(created_at: :asc) }
    validates :user_id, presence: true
    validates :title, presence: true
end

app/models/form_request.rb
class FormRequest < ActiveRecord::Base
    belongs_to :user
    
    default_scope -> { order(created_at: :asc) }
    validates :user_id, presence: true
end

app/models/glossary.rb
class Glossary < ActiveRecord::Base
    fuzzily_searchable :glossary_term
end

app/models/glossary_request.rb
class GlossaryRequest < ActiveRecord::Base
    belongs_to :user
    
    default_scope -> { order(created_at: :asc) }
    validates :user_id, presence: true
end

app/models/legal_form.rb
class LegalForm < ActiveRecord::Base
    fuzzily_searchable :legal_form_title
end

app/models/message.rb
class Message < ActiveRecord::Base
    belongs_to :user
    
    default_scope -> { order(created_at: :asc) }
    validates :user_id, presence: true
    validates :content, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
    belongs_to :user
    
    default_scope -> { order(created_at: :asc) }
    validates :user_id, presence: true
    validates :question, presence: true
end

app/models/trigram.rb
class Trigram < ActiveRecord::Base
    include Fuzzily::Model
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :messages, dependent: :destroy
	has_many :questions, dependent: :destroy
	has_many :case_requests, dependent: :destroy
	has_many :glossary_requests, dependent: :destroy
	has_many :form_requests, dependent: :destroy

	has_secure_password

	validates_confirmation_of :password

	validates_uniqueness_of :username
	validates_presence_of :username

	validates_length_of :password, :in => 6..20, :on => :create
	validates_presence_of :password_confirmation, if: :password_changed?
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @messages = @user.messages
  end

  # GET /users/new
  def new
    @user = User.new
  end
  
  def home
    @users = User.all
  end
  
  def post_message
    @user = User.find(params[:user_id])
    @current_message = @user.messages.create(content: params[:content], is_lea_response: true)
    @messages = @user.messages
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:sucess] = 'User was successfully created.'
        login @user
        format.html { redirect_to home_path }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  def require_admin
    unless current_user.admin?
      redirect_to root_path
    end
  end
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :set_case, only: [:show, :edit, :update, :destroy]

  # GET /cases
  # GET /cases.json
  def index
    @cases = Case.all
  end

  # GET /cases/1
  # GET /cases/1.json
  def show
  end

  # GET /cases/new
  def new
    @case = Case.new
  end

  # GET /cases/1/edit
  def edit
  end

  # POST /cases
  # POST /cases.json
  def create
    @case = Case.new(case_params)

    respond_to do |format|
      if @case.save
        format.html { redirect_to @case, notice: 'Case was successfully created.' }
        format.json { render :show, status: :created, location: @case }
      else
        format.html { render :new }
        format.json { render json: @case.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cases/1
  # PATCH/PUT /cases/1.json
  def update
    respond_to do |format|
      if @case.update(case_params)
        format.html { redirect_to @case, notice: 'Case was successfully updated.' }
        format.json { render :show, status: :ok, location: @case }
      else
        format.html { render :edit }
        format.json { render json: @case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cases/1
  # DELETE /cases/1.json
  def destroy
    @case.destroy
    respond_to do |format|
      format.html { redirect_to cases_url, notice: 'Case was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_case
      @case = Case.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def case_params
      params.require(:case).permit(:string, :string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def home
    @user = User.find(session[:user_id])
    @messages = @user.messages
  end
  
  def admin_home
    unless User.find(session[:user_id]).admin?
      redirect_to root_path
    end
    @users = User.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/case_requests_helper.rb
module CaseRequestsHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/form_requests_helper.rb
module FormRequestsHelper
end

app/helpers/glossaries_helper.rb
module GlossariesHelper
end

app/helpers/legal_forms_helper.rb
module LegalFormsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/session_helper.rb
module SessionHelper
	def login(user)
		session[:user_id] = user.id
		session[:is_admin] = user.admin
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def logout
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :password
    = f.text_field :password
  .actions
    = f.submit 'Save'

app/views/admin/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/admin/users/home.html.haml
%table{:class => "table"}
  %thead
    %tr
      %th Username
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.username
        %td= link_to 'Show', user, :class => "btn btn-success"

app/views/admin/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Username
      %th Password
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.username
        %td= user.password
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/admin/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/admin/users/post_message.js.erb
$('#content').val("");

$('.chat').html("<%= j render @messages %>");

$('.chat').animate({
            scrollTop: $('.chat')[0].scrollHeight
        }, 100);

app/views/admin/users/show.html.haml
.asklea
  %h1 AskLEA
  %p.lead LEA stands for legal engineer assistant
  .row.home-row
    = image_tag "lea_logo.png", :class => "img-circle", :id => "lea-logo"

.chat-box
  - if @user.messages.any?
    %ul.chat= render @messages
  - else
    %ul.chat
          
  = form_tag admin_post_message_path, remote: true, id: "message-form" do
    .message-form
      .input-group
        %input.form-control#content{:name => "content", :autocomplete => :off}
        %input{:type=>"hidden", :name => "user_id", :value => @user.id}
        %span.input-group-btn
          = submit_tag "Send!", class: "btn btn-primary", id: "post-message-button"

app/views/users/admin_home.html.haml
%table{:class => "table"}
  %thead
    %tr
      %th Username
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.username
        %td= link_to 'Show', user, :class => "btn btn-success"

app/views/users/home.html.haml
.asklea
  %h1 AskLEA
  %p.lead LEA stands for legal engineer assistant
  // .row.home-row
  // = image_tag "lea_logo.png", :class => "img-circle", :id => "lea-logo"
  .guidelines
    #glossary-guidelines.panel.panel-default
      .panel-heading Possible formats for asking definitions:
      .panel-body
        %ul
          %li What is/are #{"<term>"}?
          %li Define #{"<term>"}.
          %li Describe #{"<term>"}.
          %li What do/does #{"<term>"} mean?
    #case-guidelines.panel.panel-default
      .panel-heading Possible formats for finding/requesting cases:
      .panel-body
        %ul
          %li Case summary of #{"<case title>"}.
          %li I need the summary of #{"<case title>"}.
    #form-guidelines.panel.panel-default
      .panel-heading Possible formats for finding/requesting forms:
      .panel-body
        %ul
          %li I need a form for #{"<form title>"}.
          %li I need a #{"<form title>"} form.
          %li May I ask for a #{"<form title>"}?
          %li Provide me with a form #{"<form title>"}.
          %li Can you send me a #{"<form title>"}?
          %li Provide me a/an #{"<form title>"}.
    
      

.chat-box
  - if @user.messages.any?
    %ul.chat= render @messages
  - else
    %ul.chat
          
  = form_tag post_message_path, remote: true, id: "message-form" do
    .message-form
      .input-group
        %input.form-control#content{:name => "content", :placeholder => "Ask LEA about cases, glossary or forms...", :autocomplete => :off}
        %span.input-group-btn
          = submit_tag "Send!", class: "btn btn-primary", id: "post-message-button"